api:
  container_name: nodejs
  build: ./server
  env_file:
    - ./server/.env
  links:
    - mongodb
  ports:
    - "3000:3000"
  command: yarn run start
mongodb:
  container_name: mongodb
  image: mongo
